name: Fornax Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore tools
      run: dotnet tool restore
    - name: Run Paket
      run: dotnet paket restore
    - name: Run Fornax
      run: dotnet fornax build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_public
        publish_branch: published
        user_name: Mark Stouffer
        user_email: administrator@thefullertonian.com
        # cname: veryscontent.tech